name: test for glob expression

on:
  workflow_dispatch:
    inputs:
      dir:
        type: string
        required: true
        description: traverse directory

jobs:
  output-message:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check migration
        uses: dorny/paths-filter@v3
        id: check-migration
        with:
          filters: |
            migration-files:
              - '${{ github.event.inputs.dir }}/V**'
            migration-need-maintenance-files:
              - '${{ github.event.inputs.dir }}/[!*_NO_MAINTENANCE]*'

      - name: output message0
        if: steps.check-migration.outputs.migration-files == 'true'
        run: echo "今回はマイグレーションが発生します。"

      - name: output message1
        if: steps.check-migration.outputs.migration-files == 'true' && steps.check-migration.outputs.migration-need-maintenance-files == 'true'
        run: echo "今回はメンテナンスを含むマイグレーションが発生します。"

      - name: output message2
        if: steps.check-migration.outputs.migration-files == 'true' && steps.check-migration.outputs.migration-need-maintenance-files == 'false'
        run: echo "今回はメンテナンスを含まないマイグレーションが発生します。"

      - name: output message3
        if: steps.check-migration.outputs.migration-files == 'false'
        run: echo "今回はマイグレーションは発生しません。"
