name: test for glob expression

on: workflow_dispatch

jobs:
  output-message:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check migration
        uses: dorny/paths-filter@v3
        id: check-migration
        with:
          filters: |
            migration-files:
              - 'dir1/V**'
            migration-need-maintenance-files:
              - '!dir1/V*_NO_MAINTENANCE*'
      - name: output message1
        if: ${{ (steps.check-migration.outputs.migration-files == 'true') && (steps.check-migration.outputs.migration-need-maintenace-files == 'true') }}
        run: echo "今回はメンテナンスを含むマイグレーションが発生します。"
      - name: output message2
        if: ${{ (steps.check-migration.outputs.migration-files == 'true') && (steps.check-migration.outputs.migration-need-maintenace-files == 'false') }}
        run: echo "今回はメンテナンスを含まないマイグレーションが発生します。"
      - name: output message3
        if: ${{ steps.check-migration.outputs.migration-files == 'false' }}
        run: echo "今回はマイグレーションは発生しません。"
